# Custom Language File for Launcher Customizer

[ejs.app]
title = "TostHost Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/toster234/ModLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/toster234/ModLauncher"
supportLink = "https://github.com/toster234/ModLauncher/issues"

[ejs.welcome]
welcomeHeader = "WITAJ W TOSTHOST LAUNCHER"
welcomeDescription = "Launcher służy tylko do instalowania paczek od tostera :)"
welcomeDescCTA = "Jesteś tylko kilka klinięć od uruchomienia gry"
