[ejs.landing]
updateAvailableTooltip = "Dostępna aktualizacja"
usernamePlaceholder = "Username"
usernameEditButton = "Edytuj"
settingsTooltip = "Ustawienia"
serverStatus = "SERVER"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "WIADOMOŚCI"
launchButton = "GRAJ"
launchButtonPlaceholder = "&#8226; No Server Selected"
launchDetails = "Proszę czekać.."
newsNavigationStatus = "{currentPage} z {totalPages}"
newsErrorLoadSpan = "Checking for News.."
newsErrorFailedSpan = "Failed to Load News"
newsErrorRetryButton = "Spróbuj ponownie"
newsErrorNoneSpan = "Brak wiadomości"

[ejs.login]
loginCancelText = "Anuluj"
loginSubheader = "MINECRAFT LOGIN"
loginEmailError = "* Invalid Value"
loginEmailPlaceholder = "EMAIL OR USERNAME"
loginPasswordError = "* Required"
loginPasswordPlaceholder = "HASŁO"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "forgot password?"
loginRememberMeText = "remember me?"
loginButtonText = "LOGIN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Need an Account?"
loginPasswordDisclaimer1 = "Your password is sent directly to mojang and never stored."
loginPasswordDisclaimer2 = "{appName} is not affiliated with Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opcje logowania"
loginWithMicrosoft = "Zaloguj się z Microsoft"
loginWithMojang = "Login with Mojang"
cancelButton = "Anuluj"

[ejs.overlay]
serverSelectHeader = "Dostępne serwery"
serverSelectConfirm = "Wybierz"
serverSelectCancel = "Anuluj"
accountSelectHeader = "Wybierz konto"
accountSelectConfirm = "Wybierz"
accountSelectCancel = "Anuluj"

[ejs.settings]
navHeaderText = "Ustawienia"
navAccount = "Konto"
navMinecraft = "Minecraft"
navMods = "Mody"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "O launcherze"
navUpdates = "Aktualizacje"
navDone = "Gotowe"
tabAccountHeaderText = "Ustawienia konta"
tabAccountHeaderDesc = "Dodaj nowe konta lub zarządzaj istniejącymi."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Dodaj konto Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Dodaj konto Mojang"
minecraftTabHeaderText = "Ustawienia Minecraft"
minecraftTabHeaderDesc = "Opcje związane z uruchomieniem gry."
gameResolutionTitle = "Rozdzielczość gry"
launchFullscreenTitle = "Uruchom w trybie pełnoekranowym."
autoConnectTitle = "Automatyczne połączenie z serwerem podczas uruchamiania."
launchDetachedTitle = "Uruchom proces gry jako niezależny od launchera."
launchDetachedDesc = "Jeśli gra nie jest odłączona, zamknięcie launchera spowoduje również zamknięcie gry."
tabModsHeaderText = "Ustawienia modów"
tabModsHeaderDesc = "Włączenie lub wyłączenie modów."
switchServerButton = "Wybierz"
requiredMods = "Wymagane mody"
optionalMods = "Mody opcjonalne"
dropinMods = "Przerzuć mody"
addMods = "Dodaj mody"
dropinRefreshNote = "(F5 by odświeżyć)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Włącz lub wyłącz shadery. Uwaga, shadery będą działać płynnie tylko na mocnych konfiguracjach. Tutaj możesz dodać niestandardowe."
selectShaderpack = "Wybierz Shaderpack"
tabJavaHeaderText = "Ustawienia Javy"
tabJavaHeaderDesc = "Zarządzaj konfiguracją Java (zaawansowane)."
memoryTitle = "Pamięć"
maxRAM = "Maximum RAM"
minRAM = "Minimum RAM"
memoryDesc = "Zalecane minimum pamięci RAM to 6 gigabajty. Ustawienie wartości minimalnej i maksymalnej na tę samą wartość może zmniejszyć opóźnienie."
memoryTotalTitle = "Razem"
memoryAvailableTitle = "Dostępne"
javaExecutableTitle = "Java Executable"
javaExecSelDialogTitle = "Select Java Executable"
javaExecSelButtonText = "Choose File"
javaExecDesc = "Java executable jest sprawdzany przed uruchomieniem gry."
javaPathDesc = "Ścieżka powinna kończyć się na <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Dodatkowe opcje JVM"
jvmOptsDesc = "Opcje, które mają być przekazane do JVM podczas uruchamiania. <em>-Xms</em> and <em>-Xmx</em> nie powinny być ujęte."
launcherTabHeaderText = "Ustawienia Launchera"
launcherTabHeaderDesc = "Opcje związane z samym launcherem."
allowPrereleaseTitle = "Zezwól na aktualizacje eksperymentalne."
allowPrereleaseDesc = "Wersja deweloperska zawiera nowe funkcje, które mogą nie być w pełni przetestowane lub zintegrowane.<br>Ta opcja będzie zawsze zaznaczona, jeśli używasz już wersji deweloperskiej."
dataDirectoryTitle = "Folder z danymi"
selectDataDirectory = "Select Data Directory"
chooseFolder = "Wybierz folder"
dataDirectoryDesc = "Wszystkie pliki gry i lokalne instalacje Java będą przechowywane w tym katalogu.<br>Zrzuty ekranu i zapisy świata są przechowywane w folderze instancji dla odpowiedniej konfiguracji serwera."
aboutTabHeaderText = "O launcherze"
aboutTabHeaderDesc = "Wyświetl informacje i uwagi dotyczące wydania dla bieżącej wersji."
aboutTitle = "{appName}"
stableRelease = "Stabilna wersja"
versionText = "Wersja "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Informacje o wydaniu"
changelog = "Changelog"
noReleaseNotes = "Brak informacji o wersji"
viewReleaseNotes = "View Release Notes on GitHub"
launcherUpdatesHeaderText = "Aktualizacje Launchera"
launcherUpdatesHeaderDesc = "Pobieranie, instalowanie i przeglądanie aktualizacji dla launchera."
checkForUpdates = "Check for Updates"
whatsNew = "Co nowego"
updateReleaseNotes = "Update Release Notes"

[ejs.waiting]
waitingText = "Czekanie na Microsoft.."

[ejs.welcome]
continueButton = "CONTINUE"


[js.discord]
waiting = "Waiting for Client.."
state = "Serwer: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft Login"
microsoftLogoutTitle = "Microsoft Logout"

[js.login]
login = "LOGIN"
loggingIn = "LOGGING IN"
success = "SUCCESS"
tryAgain = "Spróbuj ponownie"

[js.login.error]
invalidValue = "* Invalid Value"
requiredValue = "* Wymagane"

[js.login.error.unknown]
title = "Unknown Error During Login"
desc = "An unknown error has occurred. Please see the console for details."

[js.landing.launch]
pleaseWait = "Proszę czekać.."
failureTitle = "Error During Launch"
failureText = "See console (CTRL + Shift + i) for more details."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "No Account Selected"

[js.landing.selectedServer]
noSelection = "No Server Selected"
loading = "Ładowanie.."

[js.landing.serverStatus]
server = "SERWER"
offline = "OFFLINE"
players = "GRACZY"

[js.landing.systemScan]
checking = "Checking system info.."
noCompatibleJava = "No Compatible<br>Java Installation Found"
installJavaMessage = "In order to launch Minecraft, you need a 64-bit installation of Java {major}. Would you like us to install a copy?"
installJava = "Install Java"
installJavaManually = "Install Manually"
javaDownloadPrepare = "Preparing Java Download.."
javaDownloadFailureTitle = "Error During Java Download"
javaDownloadFailureText = "See console (CTRL + Shift + i) for more details."
javaRequired = "Java is Required<br>to Launch"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "I Understand"
javaRequiredCancel = "Go Back"

[js.landing.downloadJava]
findJdkFailure = "Failed to find OpenJDK distribution."
javaDownloadCorruptedError = "Downloaded JDK has a bad hash, the file may be corrupted."
extractingJava = "Extracting Java"
javaInstalled = "Java Installed!"

[js.landing.dlAsync]
loadingServerInfo = "Loading server information.."
fatalError = "Błąd krytyczny"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "Please wait.."
errorDuringLaunchTitle = "Error During Launch"
seeConsoleForDetails = "See console (CTRL + Shift + i) for more details."
validatingFileIntegrity = "Validating file integrity.."
errorDuringFileVerificationTitle = "Error During File Verification"
downloadingFiles = "Downloading files.."
errorDuringFileDownloadTitle = "Error During File Download"
preparingToLaunch = "Przygotowanie do startu.."
launchingGame = "Launching game.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Gotowe. Miłego grania!"
checkConsoleForDetails = "Please check the console (CTRL + Shift + i) for more details."

[js.landing.news]
checking = "Checking for News"

[js.landing.discord]
loading = "Ładowanie gry.."
joining = "Dołącza do gry!"
joined = "Gra na modach"

[js.overlay]
dismiss = "Dismiss"

[js.settings.fileSelectors]
executables = "Executables"
allFiles = "All Files"

[js.settings.mstfLogin]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft authentication failed. Please try again."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Something Went Wrong"
errorMessage = "Microsoft logout failed. Please try again."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Wybierz konto"
selectedButton = "Wybrane konto &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Ostrzeżenie<br>To jest twoje ostatnie konto"
lastAccountWarningMessage = "Aby korzystać z launchera musisz być zalogowany na co najmniej jedno konto. Po zakończeniu będziesz musiał się ponownie zalogować.<br><br>Czy na pewno chcesz się wylogować?"
confirmButton = "Tak"
cancelButton = "Anuluj"

[js.settings.authAccountPopulate]
username = "Username"
uuid = "UUID"
selectAccount = "Wybierz konto"
selectedAccount = "Wybrane konto ✓"
logout = "Wyloguj"

[js.settings.dropinMods]
removeButton = "Usuń"
deleteFailedTitle = "Failed to Delete<br>Drop-in Mod {fullName}"
deleteFailedMessage = "Make sure the file is not in use and try again."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Serwer główny"

[js.settings.java]
selectedJava = "Wybrano: Java {version} ({vendor})"
invalidSelection = "Nieprawidłowy wybór"
requiresJava = "Requires Java {major} x64."
availableOptions = "Available Options for Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "New Release Available"
newPreReleaseTitle = "New Pre-release Available"
downloadingButton = "Pobieranie.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "Używasz najnowszej wersji"
checkForUpdatesButton = "Sprawdź aktualizacje"
checkingForUpdatesButton = "Sprawdzanie aktualizacji.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "We were unable to refresh the login for <strong>{account}</strong>. Please select another account or login again."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "Login"
selectAnotherAccountButton = "Select Another Account"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Sprawdzanie aktualizacji.."
installNowButton = "Zainstaluj teraz "
checkForUpdatesButton = "Check for Updates"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
